# Generated by Django 5.0.6 on 2024-05-16 17:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('lastname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('course', models.CharField(choices=[('Cetificate in Health Science', 'Cetificate in Health Science'), ('Certificate in Applied Technology', 'Certificate in Applied Technology'), ('Bachelor of Information Technology', 'Bachelor of Information Technology'), ('Bachelors in Business Technology', 'Bachelors in Business Technology'), ('Master of Public Health', 'Master of Public Health')], max_length=100)),
                ('entryscheme', models.CharField(choices=[('A-Level certificate', 'A-Level certificate'), ('Adult/Mature Learning', 'Adult/Mature Learning'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors')], max_length=100)),
                ('intake', models.CharField(choices=[('January Intake', 'January Intake'), ('May Intake', 'May Intake'), ('August Intake', 'August Intake')], max_length=50)),
                ('sponsorship', models.CharField(choices=[('Private', 'Public'), ('Government', ' Government'), ('Bursary', 'Bursary')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('residence', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
